### Spring properties
# Service registers under this name
spring:
  application:
    name: rombonganbelajar-microservice
#Configure Database
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    #hibernate:
     # ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/RombonganBelajarMS
    username: rombonganbelajar
    password: rombonganbelajar
    driverClassName: org.postgresql.Driver

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 2004

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
  